# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_title', models.CharField(max_length=40, unique=True)),
                ('t_date', models.CharField(max_length=40)),
                ('t_choice', models.IntegerField(choices=[('0', 'low'), ('1', 'medium'), ('2', 'high')], default=2)),
            ],
            options={
                'ordering': ['-t_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.User'),
        ),
    ]
