# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='u_id',
            new_name='u',
        ),
    ]
