# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20160316_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-u_id']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='t_choice',
            field=models.IntegerField(choices=[('0', 'not done'), ('1', 'done')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
