# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20160316_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='t_priority',
            field=models.IntegerField(choices=[('0', 'low'), ('1', 'medium'), ('2', 'high')], default=1),
        ),
    ]
