# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_todo_t_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='t_choice',
            field=models.CharField(choices=[('0', 'not done'), ('1', 'done')], max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='t_priority',
            field=models.CharField(choices=[('0', 'low'), ('1', 'medium'), ('2', 'high')], max_length=10),
        ),
    ]
